P1_adam:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P2_adam:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P3_adam:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P4_adam:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P5_adam:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P6_adam:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P7_adam:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P8_adam:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P1_adagrad:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P2_adagrad:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P3_adagrad:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P4_adagrad:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P5_adagrad:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P6_adagrad:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P7_adagrad:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P8_adagrad:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P1_sgd:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'sgd'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P2_sgd:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'sgd'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P3_sgd:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'sgd'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P4_sgd:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'sgd'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P5_sgd:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'sgd'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P6_sgd:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'sgd'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P7_sgd:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'sgd'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P8_sgd:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['64','relu'],['5','softmax']]
  dropouts: ['0.1','0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'sgd'
  epochs: '80'
  batch_size: '32'
  folds: '5'