P1_relu:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['32','relu'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P2_relu:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['32','relu'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P3_relu:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['32','relu'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P4_relu:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['32','relu'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P5_relu:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['32','relu'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P6_relu:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','relu'],['64','relu'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P7_relu:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','relu'],['64','relu'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P8_relu:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['128','relu'],['128','relu'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P1_tanh:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P2_tanh:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P3_tanh:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P4_tanh:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P5_tanh:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P6_tanh:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P7_tanh:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P8_tanh:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['128','tanh'],['128','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'