P1_LL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P2_LL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P3_LL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P4_LL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P5_LL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P6_LL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P7_LL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P8_LL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['128','relu'],['128','relu'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '32'
  folds: '5'
P1_SL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P2_SL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P3_SL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P4_SL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P5_SL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P6_SL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P7_SL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P8_SL:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['128','relu'],['128','relu'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '32'
  folds: '5'
P1_LS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '1'
  folds: '5'
P2_LS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '1'
  folds: '5'
P3_LS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '1'
  folds: '5'
P4_LS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '1'
  folds: '5'
P5_LS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '1'
  folds: '5'
P6_LS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '1'
  folds: '5'
P7_LS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '80'
  batch_size: '1'
  folds: '5'
P8_LS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['128','relu'],['128','relu'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '80'
  batch_size: '1'
  folds: '5'
P1_SS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['mri']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '1'
  folds: '5'
P2_SS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['pet']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '1'
  folds: '5'
P3_SS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['clinical']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '1'
  folds: '5'
P4_SS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['sociodemographic']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '1'
  folds: '5'
P5_SS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['fluid']
  classifiers: ['dl_1']
  layers: [['32','tanh'],['5','softmax']]
  dropouts: ['0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '1'
  folds: '5'
P6_SS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '10'
  batch_size: '1'
  folds: '5'
P7_SS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['non_imaging']
  classifiers: ['dl_1']
  layers: [['64','tanh'],['64','tanh'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adam'
  epochs: '10'
  batch_size: '1'
  folds: '5'
P8_SS:
  feature_selection: ['rf']
  data_split: 'k-fold'
  data_list: ['full_data']
  classifiers: ['dl_1']
  layers: [['128','relu'],['128','relu'],['5','softmax']]
  dropouts: ['0', '0', '0']
  loss: 'categorical_crossentropy'
  accuracy: 'categorical_accuracy'
  opt: 'adagrad'
  epochs: '10'
  batch_size: '1'
  folds: '5'